# Generated by Django 5.0 on 2023-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (0, 'Female')])),
                ('bmi', models.FloatField()),
                ('children', models.FloatField()),
                ('smoker', models.IntegerField(choices=[(0, 'Smoker'), (1, 'non-smoker')])),
                ('region', models.IntegerField(choices=[(2, 'Northeast'), (3, 'Northwest'), (0, 'Southeast'), (1, 'Southwest')])),
            ],
        ),
    ]
